import type { Metadata } from "next";
import { Inter, Zen_Dots } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";

const inter_init = Inter({ 
  subsets: ["latin"],
  variable: '--font-inter'
});

const zen_dots_init = Zen_Dots({ 
  subsets: ["latin"],
  weight: "400",
  variable: '--font-zen-dots'
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter_init.variable} ${zen_dots_init.variable}`}>
        <ThemeProvider attribute="class" defaultTheme="system">{children}</ThemeProvider>
        </body>
    </html>
  );
}
